// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/medis/go-expressive/src/App/Handlers"
)

// Injectors from wire.go:

func InitialisePingHandler() *Handlers.PingHandler {
	pingHandler := Handlers.NewPingHandler()
	return pingHandler
}
